### ISSUE TITLE
Library python 2.7 incompatible

### ISSUE THREAD

**Issue by kiddick** [oriontvv/pyaspeller#6]
According to Travis log https://travis-ci.org/kiddick/pyaspeller/jobs/111970923 there are libraries (such as unittest) only for python 3.

**Comment by kiddick** [comment]
Check PR https://github.com/oriontvv/pyaspeller/pull/7

**Comment by oriontvv** [comment]
thanks! Can you also add "requests" to requirements?

**Comment by kiddick** [comment]
@oriontvv sure
