### ISSUE TITLE
[Feature request] Example, how get full output for text

### ISSUE THREAD

**Issue by Kristinita** [oriontvv/pyaspeller#70]
### 1. Request

It would be nice, if you add in repository description, how can get the full output, use pyaspeller.

### 2. Justification

I want to use pyaspeller for checking big texts. But I can't find, how I can do it.

### 3. Expected behavior

I want to get full output to my console. For example, if I use yaspeller from command line:

```shell
D:\SashaPythonista>yaspeller --check-yo --find-repeat-words --ignore-digits --ignore-latin --ignore-roman-numerals --ignore-uppercase --ignore-urls[ERR] D:\SashaPythonista\SashaExample.txt 716 ms
-----
Typos: 3
1. Sasha (1:1, suggest: Саша, Sasha)
2. Belissimo (1:7, suggest: Белиссимо, Bellissimo, Беллиссимо, Belisimo, Belissima, Bellissima, Белисимо, Bellisimo, Беллисимо)
3. Совершенна (3:6, suggest: Совершенно, Совершена, Совершенная)
-----

Checking finished: 1.12 sec.

D:\SashaPythonista>
```

**Or** if I use [**language-check**](https://github.com/myint/language-check):

```python
>>> import language_check
>>> tool_language = language_check.LanguageTool('ru-RU')
>>> file_text = u'Sasha Belissimo! Саша Совершенна!'
>>> error_list = tool_language.check(file_text)
>>> print(*error_list, sep='\n\n')
Line 1, column 1, Rule ID: MORFOLOGIK_RULE_RU_RU
Message: Найдена орфографическая ошибка
Sasha Belissimo! Саша Совершенна!
^^^^^

Line 1, column 7, Rule ID: MORFOLOGIK_RULE_RU_RU
Message: Найдена орфографическая ошибка
Sasha Belissimo! Саша Совершенна!
      ^^^^^^^^^
>>>
```

### 4. Not helped

1. I save your [**example**](https://github.com/oriontvv/pyaspeller/blob/master/examples/example.py) as `example.py`:

Nothing output:

```shell
D:\SashaPythonista>python example.py

D:\SashaPythonista>
```

Thanks.

**Comment by oriontvv** [comment]
Good points, thank you. But I don't have time to contribute now - may be after few weeks or month. But Pull Requests are welcome)

**Comment by oriontvv** [comment]
Please checkout current state of pyaspeller. It has updated readme, example how to check big texts. About pretty output - it could be implemented with special option `--pretty` but for now it tends to be simple and follows unix-way. PRs are welcome as always. Closing this issue for now, fell free to open new but please split it with features
